version: 2.1
orbs:
  architect: giantswarm/architect@5.1.1

workflows:
  go-build:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build-luigi
          binary: luigi
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
